event_inherited();
damage_ = 1;
knockback_ = 3;
targets_ = [];
stun = false;
impact_ = false;
alarm[1] = 1;
image_speed = 0.6;
can_parry = true;
audio_play(a_player_charged_projectile_power_fire);
audio_stop_sound(a_player_reticle_charge);